name: Update Culture Organizations List

on:
  workflow_dispatch: # Lancement manuel
  schedule:
    - cron: "0 3 * * 1" # Tous les lundis à 3h du matin

jobs:
  update-culture-orgs-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: Documentation   # ✅ clone la bonne branche
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install datagouv-client

      - name: Run Culture Organizations script
        run: |
          python Documentation/data/script/selectOrganizationsTag.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add generated JSON
        run: |
          git add Documentation/data/organizations-datasets.json || echo "no JSON found"

      - name: Commit changes
        run: |
          git commit -m "Auto-update organizations list (culture) [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin Documentation
